name              "ubuntu"
maintainer        "Brian Gharibaan"
maintainer_email  "brian@jongensvantechniek.nl"
license           "MIT"
description       "Set of recipes to help setup applications on Ubuntu."
version           "1.0.0"
